# Conservative Training (60-day window)
DATASET:
  LOOKBACK_WIN: 60

TRAIN:
  LABEL: "RET5"
  BATCH_SIZE: 32
  NEPOCH: 100
  EARLY_STOP_EPOCH: 10
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.01
  VALID_RATIO: 0.2